# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_raw.ui'
#
# Created: Mon May 20 04:43:53 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PSSOptimisationMainWindow(object):
    def setupUi(self, PSSOptimisationMainWindow):
        PSSOptimisationMainWindow.setObjectName(_fromUtf8("PSSOptimisationMainWindow"))
        PSSOptimisationMainWindow.resize(582, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/calculator")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PSSOptimisationMainWindow.setWindowIcon(icon)
        PSSOptimisationMainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(PSSOptimisationMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grades_table = QtGui.QTableView(self.centralwidget)
        self.grades_table.setAlternatingRowColors(True)
        self.grades_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.grades_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.grades_table.setSortingEnabled(True)
        self.grades_table.setObjectName(_fromUtf8("grades_table"))
        self.grades_table.horizontalHeader().setStretchLastSection(True)
        self.grades_table.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.grades_table, 2, 0, 1, 1)
        self.start_here = QtGui.QWidget(self.centralwidget)
        self.start_here.setObjectName(_fromUtf8("start_here"))
        self.start_here_layout = QtGui.QFormLayout(self.start_here)
        self.start_here_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.start_here_layout.setContentsMargins(30, -1, -1, -1)
        self.start_here_layout.setObjectName(_fromUtf8("start_here_layout"))
        self.start_here_image = QtGui.QLabel(self.start_here)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_here_image.sizePolicy().hasHeightForWidth())
        self.start_here_image.setSizePolicy(sizePolicy)
        self.start_here_image.setMinimumSize(QtCore.QSize(48, 65))
        self.start_here_image.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pointingarrow")))
        self.start_here_image.setObjectName(_fromUtf8("start_here_image"))
        self.start_here_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.start_here_image)
        self.start_here_label = QtGui.QLabel(self.start_here)
        self.start_here_label.setObjectName(_fromUtf8("start_here_label"))
        self.start_here_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.start_here_label)
        self.gridLayout_3.addWidget(self.start_here, 1, 0, 1, 1)
        PSSOptimisationMainWindow.setCentralWidget(self.centralwidget)
        self.toolbar = QtGui.QToolBar(PSSOptimisationMainWindow)
        self.toolbar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolbar.setMovable(False)
        self.toolbar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolbar.setFloatable(False)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        PSSOptimisationMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.menuBar = QtGui.QMenuBar(PSSOptimisationMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 582, 23))
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_file = QtGui.QMenu(self.menuBar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_help = QtGui.QMenu(self.menuBar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_edit = QtGui.QMenu(self.menuBar)
        self.menu_edit.setObjectName(_fromUtf8("menu_edit"))
        PSSOptimisationMainWindow.setMenuBar(self.menuBar)
        self.status_bar = QtGui.QStatusBar(PSSOptimisationMainWindow)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        PSSOptimisationMainWindow.setStatusBar(self.status_bar)
        self.action_open = QtGui.QAction(PSSOptimisationMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon1)
        self.action_open.setIconVisibleInMenu(True)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_download = QtGui.QAction(PSSOptimisationMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/user")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_download.setIcon(icon2)
        self.action_download.setIconVisibleInMenu(True)
        self.action_download.setObjectName(_fromUtf8("action_download"))
        self.action_donate = QtGui.QAction(PSSOptimisationMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/favorite")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_donate.setIcon(icon3)
        self.action_donate.setIconVisibleInMenu(True)
        self.action_donate.setObjectName(_fromUtf8("action_donate"))
        self.action_settings = QtGui.QAction(PSSOptimisationMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/settings")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings.setIcon(icon4)
        self.action_settings.setMenuRole(QtGui.QAction.PreferencesRole)
        self.action_settings.setIconVisibleInMenu(True)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_about = QtGui.QAction(PSSOptimisationMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/monkey")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon5)
        self.action_about.setMenuRole(QtGui.QAction.AboutRole)
        self.action_about.setIconVisibleInMenu(True)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_graph = QtGui.QAction(PSSOptimisationMainWindow)
        self.action_graph.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/graph")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_graph.setIcon(icon6)
        self.action_graph.setIconVisibleInMenu(True)
        self.action_graph.setObjectName(_fromUtf8("action_graph"))
        self.action_quit = QtGui.QAction(PSSOptimisationMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/quit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_quit.setIcon(icon7)
        self.action_quit.setMenuRole(QtGui.QAction.QuitRole)
        self.action_quit.setIconVisibleInMenu(True)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_copy = QtGui.QAction(PSSOptimisationMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/copy")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon8)
        self.action_copy.setIconVisibleInMenu(True)
        self.action_copy.setObjectName(_fromUtf8("action_copy"))
        self.action_cut = QtGui.QAction(PSSOptimisationMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cut")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cut.setIcon(icon9)
        self.action_cut.setIconVisibleInMenu(True)
        self.action_cut.setObjectName(_fromUtf8("action_cut"))
        self.action_paste = QtGui.QAction(PSSOptimisationMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/paste")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon10)
        self.action_paste.setIconVisibleInMenu(True)
        self.action_paste.setObjectName(_fromUtf8("action_paste"))
        self.action_select_all = QtGui.QAction(PSSOptimisationMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/selectall")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select_all.setIcon(icon11)
        self.action_select_all.setIconVisibleInMenu(True)
        self.action_select_all.setObjectName(_fromUtf8("action_select_all"))
        self.toolbar.addAction(self.action_download)
        self.toolbar.addAction(self.action_open)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_settings)
        self.toolbar.addAction(self.action_donate)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_graph)
        self.menu_file.addAction(self.action_download)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_settings)
        self.menu_file.addAction(self.action_quit)
        self.menu_help.addAction(self.action_donate)
        self.menu_help.addAction(self.action_about)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addAction(self.action_select_all)
        self.menu_edit.addAction(self.action_graph)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_edit.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(PSSOptimisationMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PSSOptimisationMainWindow)

    def retranslateUi(self, PSSOptimisationMainWindow):
        PSSOptimisationMainWindow.setWindowTitle(QtGui.QApplication.translate("PSSOptimisationMainWindow", "PSSOptimisation", None, QtGui.QApplication.UnicodeUTF8))
        self.start_here_label.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "start here!", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("PSSOptimisationMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_file.setTitle(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_help.setTitle(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_edit.setTitle(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Get your grades from a previously saved HTML file with your grades", None, QtGui.QApplication.UnicodeUTF8))
        self.action_download.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Download grades", None, QtGui.QApplication.UnicodeUTF8))
        self.action_download.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Get your grades from PSSO by inserting your log-in credentials", None, QtGui.QApplication.UnicodeUTF8))
        self.action_donate.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.action_donate.setIconText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.action_donate.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Send the author of this application a small donation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "S&ettings", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setIconText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.action_settings.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Change settings of this program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&About PSSOptimisation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_graph.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Show &Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.action_graph.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Show or hide the graph", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Quit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Copy selection to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.action_cut.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.action_cut.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Copy selection to clipboard and remove it", None, QtGui.QApplication.UnicodeUTF8))
        self.action_paste.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_paste.setToolTip(QtGui.QApplication.translate("PSSOptimisationMainWindow", "Paste from clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.action_select_all.setText(QtGui.QApplication.translate("PSSOptimisationMainWindow", "&Select all", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
